# Generated by Django 4.2.1 on 2023-10-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0017_produs_image_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', null=True, upload_to='car/')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produs.produs')),
            ],
        ),
    ]
