# Generated by Django 4.2.1 on 2023-12-12 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0019_delete_servicii_produs_price1_produs_price2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdusEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('producator', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ImagesEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', null=True, upload_to='car2/')),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produs.produsex')),
            ],
        ),
    ]
