# Generated by Django 4.2.1 on 2023-12-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0020_produsex_imagesex'),
    ]

    operations = [
        migrations.AddField(
            model_name='produsex',
            name='cutia',
            field=models.IntegerField(choices=[(0, 'Manual'), (1, 'Automat'), (2, 'Not specified')], default=2),
        ),
        migrations.AddField(
            model_name='produsex',
            name='motor',
            field=models.IntegerField(choices=[(0, 'Diesel'), (2, 'Hybrid'), (1, 'Petrol'), (3, 'Electric'), (4, 'Petrol-Hybrid'), (5, 'Petrol-Gaz'), (6, 'Not specified')], default=6),
        ),
    ]
