# Generated by Django 4.2.1 on 2023-10-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0020_rename_coments_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='usere',
        ),
    ]
