# Generated by Django 4.2.1 on 2023-12-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0022_produsex_limita_de_km_produsex_caroserie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produsex',
            name='Limita_de_KM',
        ),
        migrations.RemoveField(
            model_name='produsex',
            name='caroserie',
        ),
        migrations.RemoveField(
            model_name='produsex',
            name='descriere',
        ),
        migrations.RemoveField(
            model_name='produsex',
            name='numar_pasageri',
        ),
        migrations.RemoveField(
            model_name='produsex',
            name='numar_usi',
        ),
    ]
