# Generated by Django 4.2.1 on 2023-12-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0024_produsex_limita_de_km_produsex_caroserie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produsex',
            name='price1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produsex',
            name='price2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produsex',
            name='price3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produsex',
            name='price4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produsex',
            name='price5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
