# Generated by Django 4.2.1 on 2023-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0025_alter_produs_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='produs',
            name='total_rating2',
            field=models.FloatField(default=0.0),
        ),
    ]
