# Generated by Django 4.2.1 on 2023-12-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0026_produsex_an_produsex_capacitate_cilindrica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='car2/'),
        ),
        migrations.DeleteModel(
            name='ImagesEx',
        ),
        migrations.DeleteModel(
            name='ProdusEx',
        ),
    ]
