# Generated by Django 4.2.1 on 2023-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0026_produs_total_rating2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='total_rating2',
            field=models.FloatField(default=5.0),
        ),
    ]
