# Generated by Django 4.2.1 on 2023-10-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0027_alter_produs_total_rating2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produs',
            name='total_rating2',
        ),
    ]
