# Generated by Django 4.2.1 on 2023-12-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produs', '0027_alter_images_image_delete_imagesex_delete_produsex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='car/'),
        ),
    ]
