# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Server

steps:
- task: CmdLine@2
  inputs:
    script: |
      ls

- task: DockerCompose@0
  displayName: 'Run Docker Compose'
  inputs:
    action: 'Build services'
    dockerComposeFile: 'docker-compose.yml'
    projectName: 'yourapp'
    buildImages: true
- task: DockerCompose@0
  displayName: 'Down Docker Compose'
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeFile: 'docker-compose.yml'
    projectName: 'yourapp'
    dockerComposeCommand: 'down'
    


- task: DockerCompose@0
  displayName: 'Up Docker Compose'
  inputs:
    action: 'Run a Docker Compose command'
    dockerComposeFile: 'docker-compose.yml'
    projectName: 'yourapp'
    dockerComposeCommand: 'up'
    arguments: '-d'
