version: '3'

services:
  frontend:
    image: frontend
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      django:
        condition: service_healthy

  django:
    image: backend
    build: Backend
    command: python Backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "python3", "Backend/manage.py", "migrate"]

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: mariadb
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
